import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import logo from '../public/empicode logo.png';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={logo}/>
        <a href="/privateportal">Open private portal</a>
        <h1 className={styles.title}>
          Welcome to EmpiCode!
        </h1>
      </main>

      <footer className={styles.footer}>
          <p>Powered by NorthView Mock Trial Academy</p>
        
      </footer>
    </div>
  )
}
